# -*- coding: utf-8 -*-
import re

import logging
log = logging.getLogger("relic")

# For each license, 'match' is a regexp which identifies that license or
# license family uniquely, when matched against a large runon string of the
# entire comment. 'subs' is a set of sub-flavours of that license. Once a type
# is detected, matches are run against the 'match' member of all the subs. If
# none are detected, you have the base flavour; otherwise you have the
# sub-flavour. This can happen recursively (see 'bsd2').
#
# Once a block has been identified as containing a particular license, you
# search from the start for a line matching 'start', and from the end
# for a line matching 'end', and take all the text in between.
#
# License tags must be unique throughout the structure.
_license_parts = {
    'mpl11': {
        'start':  r"The contents of this file are subject to the",
        'match':  r"subject to the Mozilla Public License Version 1.1",
        'end':    r"Contributor|All Rights Reserved|Initial Developer",
        'subs': {
            'mplgpllgpl': { # Mozilla
                'start':  r"The contents of this file are subject to the",
                'match':  r"Alternatively, the .*either the GNU General",
                'end':    r"terms of any one of the MPL, the GPL or the LGPL"
            },            
        }
    },
    'mpl2': {
        'start':  r"Source Code Form [Ii]s subject to the terms of the Mozilla",
        'match':  r"Mozilla Public License, v\. 2\.0",
        'end':    r"You can obtain one at http://mozilla\.org/MPL/2\.0/"
    },
    'gpl3': {
        'start':  r"This program is free software: you can redistribute it",
        'match':  r"GNU General Public License.*version 3 of the License",
        'end':    r"along with this program"
    },
    'gpl2': {
        'start':  r"This program is free software; you can redistribute it",
        'match':  r"GNU General Public License.*version 2 of the License",
        'end':    r"0211[01].*USA",
        'subs': {
            'gplexceptionautoconf': {
                'start':  r"This program is free software; you can",
                'match':  r"configuration script generated by Autoconf",
                'end':    r"for the rest of that program"
            },
        }
    },
    'lgpl2': {
        'start':  r"This (library|program) is free software; you can redistribute it",
        'match':  r"GNU (Lesser|Library) General Public License.*version 2",
        'end':    r"0211[01].*USA|lgpl\.html",
        'subs': {
            'lgplmplgpl': {
                'start':  r"This library is free software; you can",
                'match':  r"Alternatively, the.*Mozilla Public License",
                'end':    r"\(at your option\) any later version"
            },
            'lgplmpl': { # Cairo
                'start':  r"This library is free software; you can",
                'match':  r"should have received a copy of the MPL along with",
                'end':    r"governing rights and limitations"
            }
        }
    },
    'gplexceptionbison': {
        'start':  r"As a special exception, you may",
        'match':  r"of the Bison parser skeleton",
        'end':    r"of Bison"
    },
    'apache2': {
        'start':  r"Licensed under the Apache License, Version 2\.0",
        'match':  r"Licensed under the Apache License, Version 2\.0",
        'end':    r"the License\.|licenses/LICENSE-2\.0"
    },
    'hpnd': {
        'start':  r"Permission to use, copy, modify,(?: and)? distribute",
        'match':  r"Permission to use, copy, modify,(?: and)? distribute",
        'end':    r"OF THIS SOFTWARE|express or implied warranty" + \
                  r"|written prior permission|supporting documentation"
    },
    'mit': {
        'start':  r"Permission is hereby granted, " + \
                  r"(?:free of charge|without written agreement)" + \
                  r"|licensed under the MIT",
        'match':  r"Permission is hereby granted, " + \
                  r"(?:free of charge|without written agreement)" + \
                  r"|licensed under the MIT",
        'end':    r"SOFTWARE\.|copyright holder|OR MODIFICATIONS",
        'subs': {
            'mitgpl': { # jQuery
                'start': r"Dual licensed under the MIT",
                'match': r"Dual licensed under the MIT.*and GPL",
                'end':   r"jquery\.com/License|licenses\."
            },
            'suitablebsdish': {
                'start': r"Permission is hereby granted, free of charge",
                'match': r"Neither the names of Suitable Systems",
                'end':   r"WITH THE SOFTWARE"
            }
         }
    },
    'bsd2': {
        'start':  r"Redistribution and use of this software" + \
                  r"|Redistribution and use in source and binary forms",
        'match':  r"Redistributions in binary form must reproduce",
        'end':    r"SUCH DAMAGE",
        'subs': {
            'bsd3': {
                'start':  r"Redistribution and use of this software" + \
                          r"|Redistribution and use in source and binary",
                'match':  r"name.*may not be used to" + \
                          r"|Neither the name.*may be used to",
                'end':    r"SUCH DAMAGE",
                'subs': {
                    'bsd4': {
                        'start':  r"Redistribution and use of this software" + \
                                  r"|Redistribution and use in source and",
                        'match':  r"advertising materials",
                        'end':    r"SUCH DAMAGE"
                    },
                }
            }
        }
    },
    'bsdfileref': {
        'start':  r"Licensed under the New BSD license" + \
                  r"|The program is distributed under terms of BSD" + \
                  r"|Use of this source code is governed by a BSD-style",
        'match':  r"Licensed under the New BSD license" + \
                  r"|The program is distributed under terms of BSD" + \
                  r"|Use of this source code is governed by a BSD-style",
        'end':    r"licenses/(BSD-3-Clause|bsd-license.php)|LICENSE|source tree"
    },
    'gnupermissive': {
        'start':  r"Copying and distribution of this file, with or without",
        'match':  r"Copying and distribution of this file, with or without",
        'end':    r"notice are preserved"
    },
    'icu': {
        'start':  r"ICU License - ICU",
        'match':  r"ICU License - ICU",
        'end':    r"respective owners"
    },
    'jpnic': {
        'start':  r"The following License Terms and Conditions apply",
        'match':  r"The name of JPNIC may not be used",
        'end':    r"POSSIBILITY OF SUCH DAMAGES"
    },
    'ofl10': {
        'start':  r"This Font Software is licensed",
        'match':  r"SIL Open Font License, Version 1\.0",
        'end':    r"IN THE FONT SOFTWARE"
    },
    'ofl11': {
        'start':  r"This Font Software is licensed",
        'match':  r"SIL Open Font License, Version 1\.1",
        'end':    r"IN THE FONT SOFTWARE"
    },
    'iscgeneral': {
        'start':  r"This program is made available under an ISC-style license",
        'match':  r"This program is made available under an ISC-style license",
        'end':    r"file LICENSE for details"
    },
}

starts = {}
ends = {}

def _compile(parts):
    matches = []
    for (name, patterns) in parts.items():
        matches.append("(?P<" + name + ">" + patterns['match'] + ")")
        starts[name] = re.compile(patterns['start'])
        ends[name]   = re.compile(patterns['end'])
        if 'subs' in patterns:
            _compile(patterns['subs'])
    parts['_match_re'] = re.compile("|".join(matches))

_compile(_license_parts)


def id_license(comment):
    linear_comment = canonicalize_comment(comment)

    tag = _id_license_against(_license_parts, linear_comment)

    if tag:
        log.debug("Found license: %s" % tag)
        return tag
    else:
        log.debug("No license found in comment")
        return None


def _id_license_against(parts, comment):
    match = parts['_match_re'].search(comment)
    
    if match:
        hits = match.groupdict()
        tags = [hit for hit in hits if hits[hit]]
        if len(tags) > 1:
            log.warning("Found multiple licenses: %s" % "/".join(tags))
        tag = tags[0]
        log.debug("License match: %s" % tag)
        if 'subs' in parts[tag]:
            log.debug("Checking for sub-types")
            newtag = _id_license_against(parts[tag]['subs'], comment)
            if newtag:
                log.debug("Overriding license %s with %s" % (tag, newtag))
                tag = newtag
            else:
                log.debug("Sticking with base flavour")
        
        return tag

    return None


def extract_copyrights_and_license(text, tag):
    license = []
    copyrights = []
    in_copyrights = False

    start_line = -1
    end_line = -1    
    
    # Find copyrights and start
    for i in range(len(text)):
        line = text[i]
        
        if starts[tag].search(line):
            log.debug("First license line: %s" % line)
            start_line = i
            break
        
        if re.search("copyright [\d\(©]", line, re.IGNORECASE):
            log.debug("Copyright line: %s" % line)
            copyrights.append(line)
            in_copyrights = True
            continue
        
        if in_copyrights:
            if re.search("^\s*$", line): 
                log.debug("Blank line (while in copyrights)")
                # Blank line
                in_copyrights = False
            else:
                # Continuation line
                log.debug("CopyConti line: %s" % line)
                copyrights[-1] = copyrights[-1] + " " + line

    if start_line == -1:
        log.warning("Can't find start line for requested license '%s'!" % tag)
        return [], []
        
    # Find license end, starting from text end (defaulting to text end)
    end_line = len(text)
    for i in range(len(text) - 1, -1, -1):
        line = text[i]
        
        if ends[tag].search(line):
            log.debug("Last license line: %s" % line)
            end_line = i
            break
    else:
        log.warning("Can't find end line for requested license '%s'!" % tag)

    log.debug("License extends from line %i to %i" % (start_line, end_line))
    license = text[start_line:end_line + 1]

    license    = _remove_initial_rubbish(license)
    copyrights = _remove_initial_rubbish(copyrights)
    
    return copyrights, license


def _remove_initial_rubbish(comment):
    # Can't just remove all leading whitespace line-by-line as that can mess 
    # up formatting. However, we can remove any common prefix of whitespace or
    # random rubbish. For the moment, take off whatever's on the first line.
    if not comment:
        return comment
    
    match = re.search("^([\s\*#\-/]+)", comment[0])
    if match:
        rubbish = match.group(0)
        for i in range(len(comment)):
            # Last char is optional; it can be pre-text whitespace which
            # doesn't appear on blank lines
            comment[i] = re.sub("^" + re.escape(rubbish) + "?", "", comment[i])

    return comment

    
# XXX these are currently in 2 places
def canonicalize_comment(comment):
    line = " ".join(comment)
    line = collapse_whitespace(line)
    
    return line


def collapse_whitespace(line):
    # Collapse whitespace
    line = re.sub("\s+", " ", line)

    # Strip leading and trailing whitespace
    line = re.sub("^\s", "", line)
    line = re.sub("\s$", "", line)
    
    return line
