#!/usr/bin/python
# -*- coding: utf-8 -*-
###############################################################################
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
###############################################################################
#
# Produce various stats about a slic output file.

import json
import sys
import re
from slic_results import SlicResults

# Load occurrence data file
occurrences = SlicResults()
occurrences.load_json(sys.argv[1])

file_count = 0
boilerplate_count = 0
licenses = {}

for data in occurrences.itervalues():
    boilerplate_count = boilerplate_count + 1
    file_count = file_count + len(data['files'])
    tag = data['tag']
    tag = re.sub("_.*", "", tag)
    licenses[tag] = 1
    
print "Unique license boilerplate instances: %i" % boilerplate_count
print "Unique license tags: %i" % len(occurrences)
print "Unique licenses: %i" % len(licenses)
print "Files: %i" % file_count

for tag in sorted(licenses.keys()):
    print tag
