#!/usr/bin/python
# -*- coding: utf-8 -*-
###############################################################################
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
###############################################################################
#
# Throwaway script to count number of files in a slic output file.

import json
import sys

# Load occurrence data file
occurrences = json.load(open(sys.argv[1]))

# Rejig data structure so top-level key is the tag instead of the license
# text hash, and value is a list of the corresponding license objects
bytag = {}

for occurrence in occurrences:
    tag = occurrence['tag']
    if tag in bytag:
        bytag[tag].append(occurrence)
    else:
        bytag[tag] = [occurrence]

count = 0
for tag in bytag.keys():
    licset = bytag[tag]
    for lic in licset:
        count = count + len(lic['files'])

print "Files: %i" % count
